### ISSUE TITLE
arrange.() with tidyselect

### ISSUE THREAD

**Issue by marianschmidt** [markfairbanks/tidytable#134]
Feature request: It would be great to use arrange.() with tidyselect functions, e.g. tidyselect::any_of().

I don't know why, but in dplyr, it is implemented with across(), so maybe arrange_across.() would be an option, although I think, it would be more logical if arrange.() would directly understand tidyselect, since it is not really doing an operation across multiple columns, but rather across the data using column names as arguments.

**Comment by markfairbanks** [comment]
Yep, I can definitely work on adding this.

> I don't know why, but in dplyr, it is implemented with across()

**Short answer**
tidyselect unfortunately won't work inside of `arrange.()`, and I'll have to implement it as `arrange_across.()`.

**Long answer**
This is actually good timing for this feature request - I debated adding tidyselect to `arrange.()` a couple weeks ago, and I stumbled into why dplyr uses `across()`.

tidyselect uses a minus sign `-` to drop columns, whereas `dplyr::arrange()` uses the `-` sign to indicate "descending order". This causes the tidyselect to fail if implemented inside `arrange()`, because it uses the `-` to drop columns.

Using tidyselect inside of `select.()`:
``` r
library(tidytable, warn.conflicts = FALSE)

test_df <- tidytable(x1 = 1:3,
                     x2 = 1:3,
                     y = c("a", "a", "b"))

# select all columns that start with "x"
test_df %>%
  select.(starts_with("x"))
#> # tidytable [3 × 2]
#>      x1    x2
#>   <int> <int>
#> 1     1     1
#> 2     2     2
#> 3     3     3

# drop all columns that start with "x"
test_df %>%
  select.(-starts_with("x"))
#> # tidytable [3 × 1]
#>   y    
#>   <chr>
#> 1 a    
#> 2 a    
#> 3 b
```

So if we were to try and apply this to `arrange.()`, it's tough to know what the user is trying to do.

* Example 1 works
* Example 2 & 3 now could mean multiple things
```r
# arrange by all columns that start with "x"
test_df %>%
  arrange.(starts_with("x"))

# arrange all columns that start with "x" in descending order?
# or arrange all columns that don't start with "x" in ascending order?
test_df %>%
  arrange.(-starts_with("x"))

# arrange column "y" in descending order?
# or "unselect" column y and arrange by the "x" columns?
test_df %>%
  arrange.(-y)
```
