### ISSUE TITLE
Tidytable removes sf class from object hindering integration with spatial data analysis workflows

### ISSUE THREAD

**Issue by Robinlovelace** [markfairbanks/tidytable#254]
As illustrated in the reproducible example below.

``` r
library(tidytable)
#> 
#> Attaching package: 'tidytable'
#> The following object is masked from 'package:stats':
#> 
#>     dt
library(tmap)
tmap_mode("view")
#> tmap mode set to interactive viewing
nc = sf::st_read(system.file("shape/nc.shp", package="sf"))
#> Reading layer `nc' from data source `/home/robin/R/x86_64-pc-linux-gnu-library/4.0/sf/shape/nc.shp' using driver `ESRI Shapefile'
#> Simple feature collection with 100 features and 14 fields
#> Geometry type: MULTIPOLYGON
#> Dimension:     XY
#> Bounding box:  xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> Geodetic CRS:  NAD27
nc1 = nc %>% slice.(1)
nc2 = nc %>% dplyr::slice(1)
class(nc1)
#> [1] "tidytable"  "data.table" "data.frame"
class(nc2)
#> [1] "sf"         "data.frame"
qtm(nc1)
#> Error: Object nc1 is neither from class sf, stars, Spatial, nor Raster.
qtm(nc2)
#> Linking to GEOS 3.9.0, GDAL 3.2.1, PROJ 7.2.1
```

![](https://i.imgur.com/tSCMFPu.png)

<sup>Created on 2021-04-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by moutikabdessabour** [comment]
This could be easily fixed by changing `add_tidytable_class` to not overwrite the class of the data.frame i.e `class(x) <-  unique(c("tidytable", "data.table", class(x))) `

**Comment by markfairbanks** [comment]
@Robinlovelace Unfortunately this one can't be fixed for tidytable. The initial issue would be fixed by @moutikabdessabour's suggestion, but apparently there is a deeper incompatibility between data.table and sf:
https://github.com/r-spatial/sf/issues/428
https://github.com/Rdatatable/data.table/issues/2273

Until those are fixed tidytable functions won't ever be able to work with sf objects.

@moutikabdessabour I think your suggested change probably should be implemented in some form either way. I'm going to open a couple other issues that are based on your change:
1) Implement `.tidytable` methods
   - Note: I'll take care of this one. There was some odd issue with environments/data masks last time I tried this. I'll have to go back and see if I can figure out the issue.
2) Allow tidytable subclasses (by updating the `add_tidytable_class()` internal helper)
