### ISSUE TITLE
read_delim. and write_delim.

### ISSUE THREAD

**Issue by AltfunsMA** [markfairbanks/tidytable#307]
`tidytable` does a great job of replacing the need for me to load the tidyverse. The only two exceptions are the `stringr` and `readr` packages. The former is clearly out of scope but replicating `data.table` functionality should include a wrapper around `fread` and `fwrite`?

In addition, one of the advantages of the tidy tools is that they tidy the output to the console, which is great for a quick check that everything is as expected. I find myself adding `as_tidytable()` after every `fread`, which is cumbersome.

**Comment by markfairbanks** [comment]
Hmm I'll have to think about this one. I have been more focused on `tidytable` being a `dplyr`/`tidyr` replacement. I feel like creating `read_delim.`/`write_delim.` would mean I should create `read_/`write_csv`, etc. Not sure if I want to go that route.

One option is to reexport `fread` and `fwrite` so that you can use them without loading `data.table`. However you would still need to write `as_tidytable()` at the end.

Maybe and `fread.()` and `fwrite.()` that are simple wrappers that return tidytables?

**Comment by AltfunsMA** [comment]
I was thinking about your last option, the name was perhaps misleading. I
used read/write_delim. because it is more what I'd call fread/fwrite if
they were in the tidyverse.

As far as I'm concerned, just having fwrite.() returning tidytables would
be terrific!

Mark Fairbanks ***@***.***> 於 2021年8月19日 週四 02:44 寫道：

**Comment by markfairbanks** [comment]
All set

``` r
pacman::p_load(tidytable)

fread.(
  "A,B
  1,2
  3,4"
)
#> # A tidytable: 2 × 2
#>       A     B
#>   <int> <int>
#> 1     1     2
#> 2     3     4
```

**Comment by markfairbanks** [comment]
@AltfunsMA - I decided to add dotless versions of functions to tidytable (and keep the `verb.()` versions as well). See #572 for extra reasoning. The reasoning more or less lines up exactly with what you mentioned in https://github.com/markfairbanks/tidytable/issues/374#issuecomment-1047328344.

I started the process, but I'm not sure exactly what to do here. Should I just overwrite `fread()` from `data.table` so that it returns a data.table? Or should I do something like `f_read()`?

**Comment by AltfunsMA** [comment]
It is a bit of a special case but following the logic in #572 I think fread() makes the most sense. You're creating a simple drop-in replacement for dplyr/tidyr, so the behaviour should be the same for these two data.table functions. In my experience, the point of using tidytable is not to have to use data.table, so I almost can't see the point of ensuring data.table::fread() is accessible without prefix.
