### ISSUE TITLE
Default name in count() is N, while dplyr uses n

### ISSUE THREAD

**Issue by Kudusch** [markfairbanks/tidytable#377]
The default name for the tally variable in the `dplyr::count()` function is `n`, while it is `N` in the `tidytable::count()` function. This makes it a bit harder to use tidytable as a drop-in replacement or when comparing the two packages. 

If this is intentional, this issue can be closed. But if it's not, the fix would be pretty easy to implement:

```
 if (is.null(name)) {
    name <- "n"
  }
```
In lines 50–52 and the documentation in line 16, in [count()](https://github.com/markfairbanks/tidytable/blob/main/R/count.R)

**Comment by markfairbanks** [comment]
Unfortunately I don't think this can be changed at this point. As much as I would like to make it `n`, it's been too long as `N`. Any change now would cause errors in user's code that have been long time users of the package.

Very very very early on with tidytable I wasn't quite as worried about it being a perfect replacement for tidyverse syntax. At that time I used this translation - which is a more direct data.table translation for count:

``` r
library(data.table)

df <- data.table(x = c("a", "a", "b"))

df[, .N, by = x]
#>         x     N
#>    <char> <int>
#> 1:      a     2
#> 2:      b     1
```

You can see the column name is an auto-generated `N`.  The code has since been updated to be more "tidyverse-like" internally, but I've had to keep the original name.
