### ISSUE TITLE
`eval_tidy` failures: induced by differences in `dplyr::mutate` and `tidytable::dt_mutate`

### ISSUE THREAD

**Issue by xiaodaigh** [markfairbanks/tidytable#39]
I think there is a difference between how dplyr treats quoted code and how `tidytable` treats them.

This is a blocking issue for integrating `tidytable` with `disk.frame`, see https://github.com/xiaodaigh/disk.frame/pull/271

```
fn = function(a,b) {
  a + b
}

# dplyr seems to be able to handle this correctly
mwe_mutate = function(...) {
  quo_dotdotdot = rlang::enquos(...)
  data = data.frame(num = 1:100)
  code = rlang::quo(mutate(data, !!!quo_dotdotdot))  
  rlang::eval_tidy(code)
}

mwe_mutate(b = fn(num, num))

# tidytable seems to fail 
mwe_dt_mutate = function(...) {
  quo_dotdotdot = rlang::enquos(...)
  data = data.frame(num = 1:100)
  code = rlang::quo(dt_mutate(data, !!!quo_dotdotdot))  
  rlang::eval_tidy(code)
}

mwe_dt_mutate(b = fn(num, num)) # this gives an error
```

**Comment by markfairbanks** [comment]
This issue comes from the fact that quosures don't always work nicely inside of `data.table` operations. If I remember correctly they work ok for arrange/filter type operations, but won't work at all inside of `data.table`'s mutate operation.

For this reason you can't use `rlang::enquos()`, and must instead use `rlang::enexprs()`:

```r
mwe_dt_mutate = function(...) {
  expr_dotdotdot = rlang::enexprs(...)
  data = data.frame(num = 1:100)
  code = rlang::quo(dt_mutate(data, !!!expr_dotdotdot))
  rlang::eval_tidy(code)
}

mwe_dt_mutate(b = fn(num, num))
```

**Comment by markfairbanks** [comment]
Here's a good example of a very basic mutate translation:

```r
quo_dt_mutate <- function(.data, ...) {
  dots <- enquos(...)
  
  eval_tidy(expr(
    .data[, ':='(!!!dots)][]
  ))
}

expr_dt_mutate <- function(.data, ...) {
  dots <- enexprs(...)
  
  eval_tidy(expr(
    .data[, ':='(!!!dots)][]
  ))
}

test_df <- data.table(x = 1:3)

quo_dt_mutate(test_df, double_x = x * 2) # Fails

expr_dt_mutate(test_df, double_x = x * 2) # Works
```

**Comment by markfairbanks** [comment]
This issue is now fixed in the new version of tidytable up on CRAN (v0.5.0).

Note there's been a small syntax change where all functions now use `verb.()` syntax instead of `dt_verb()`. For example `dt_mutate()` has been renamed to `mutate.()`.

The `dt_` versions still exist in tidytable, but it seems like a lot of packages are using that prefix so I decided to change things during version v0.4.0.

``` r
library(tidytable, warn.conflicts = FALSE)

fn = function(a,b) {
  a + b
}

mwe_dt_mutate = function(...) {
  quo_dotdotdot = rlang::enquos(...)
  data = data.frame(num = 1:100)
  code = rlang::quo(mutate.(data, !!!quo_dotdotdot))  
  rlang::eval_tidy(code)
}

mwe_dt_mutate(b = fn(num, num)) %>% head()
#>    num  b
#> 1:   1  2
#> 2:   2  4
#> 3:   3  6
#> 4:   4  8
#> 5:   5 10
#> 6:   6 12
```

**Comment by xiaodaigh** [comment]
I will take a look. Busy with work and some Julia open source work atm.

**Comment by markfairbanks** [comment]
Sounds good, if there's anything I can help with let me know
