### ISSUE TITLE
Check validity of verb.() function names

### ISSUE THREAD

**Issue by markfairbanks** [markfairbanks/tidytable#46]
@moodymudskipper 

I sent you this in reddit as well, I wasn't sure how often you checked your account.

I have an advanced R question and hoped you might be able to provide some guidance.

I created this package (tidytable) to replicate tidyverse syntax with a data.table/rlang backend.

Originally the functions followed the syntax of `dt_verb()`. I was about to submit a big update to CRAN that would replace this syntax with `verb.()` (while adding function deprecation warnings for the `dt_` syntax).

My question is this - is it a bad idea to use `verb.()`? Is this against best practices since the "." is used for S3 methods? The package passes tests, passes `devtools::check()`, and all S3 methods work (ex: mutate..data.frame()). But is this a bad idea?

Thanks for any help - I'll be honest I'm not sure who to reach out to with this issue

**Comment by moodymudskipper** [comment]
Hi!

I'm flattered you think about me for an advanced question :).
I think it's fine. About the dot, as far as I know : 

* dots in the middle of the name are often discouraged because there is an ambiguity with S3 methods but it doesn't apply to your case
* I think these can however fire the autocomplete in your ide, but i don't think it will impact the experience that much
* dots at the start of the name will make your variable not listed by ls (by default), so should not be done without a good reason, parameter names are ok.
* two dots at the start of the name should be be avoided because (I think, maybe I'm wrong) they're sometimes used when you need a variable in your environment but make sure they don't mask a realistic variable name, so better stay off those to avoid weird issues.

The other issue is that `.` doesn't say anything other than "it's a variant", so when you see `select_`, `select` and `select.` it can be confusing, but on the other hand it makes things readable so I think it's a reasonable choice.

Do you know about tidyfast ? I never really used it much but it seems to do the same kind of things as your package, and had the same function names before you changed yours.

For this kind of issues i'd typically tweet, but pinging we on github is fine too.

Good luck in any case. It seems like people like it a lot already!

**Comment by markfairbanks** [comment]
Thanks for the response, I really appreciate it. Those points all make sense. I think I'll move forward with the `verb.()` syntax.

As for tidyfast - I contributed `dt_pivot_wider()` & `dt_pivot_longer()` to tidyfast a while back when both of our packages used the `dt_` prefix . (Since that time I switched my package to using an `rlang` backend and ended up remaking both functions for my package as well.)

One of the reasons I wanted to switch to `verb.()` was because a few packages seem to have adopted the `dt_` style (like [maditr](https://github.com/gdemin/maditr) and tidyfast), and I wanted to figure out a way to have a different syntax that was still recognizable to tidyverse users.

Thanks again for your help!
