### ISSUE TITLE
Some dot functions no longer works

### ISSUE THREAD

**Issue by jfdesomzee** [markfairbanks/tidytable#600]
Hi,

I've downloaded the newest version 0.8.1.9 and I notic that some dot functions no longer work:
``
iris %>% tidytable::mutate_rowwise.(S = Sepal.Length+1)
``
Error in UseMethod("mutate_rowwise.") : 
  no applicable method for 'mutate_rowwise.' applied to an object of class "c('tidytable', 'data.table', 'data.frame')"

The same for slice_tail.
mutate_rowwise and slice_tail on the contrary works

**Comment by markfairbanks** [comment]
Hmm this is odd. I see what the issue is and it's an easy fix. But I have tests for these functions that still run.

**Comment by markfairbanks** [comment]
These should work now. I check all of the functions to make sure they were exported correctly. If you do happen to run into any more let me know.

**Comment by markfairbanks** [comment]
@mattsams89 - have you run into any issues with `verb.()` functions that no longer work?

For some reason my tests passed on these functions even though they caused errors when used normally. I believe I have fixed all possible issues, but if you run into anything please let me know.

(Thanks in advance - since I know you have the dev version installed any help is appreciated.)

**Comment by mattsams89** [comment]
I was getting some weirdness with an `ifelse.()` and `case_when.()` being passed to flextable requiring NA handling a little earlier, but I think that was an artifact of flextable doing something similar to quarto with their `ifelse` handling. The removal of `ifelse` seems to have fixed it, though. I'll keep an eye out and let you know if I run into any issues.

**Comment by markfairbanks** [comment]
Awesome, thanks.
