### ISSUE TITLE
grouping with tidytable does not transfer to dplyr

### ISSUE THREAD

**Issue by statzhero** [markfairbanks/tidytable#691]
I suppose one cannot mix the `dplyr` and  `tidytable` after grouping? I don't know why I thought this would work. Perhaps because something like `tidytable::arrange()` _could_ be mixed into without any bad side effects I can think of. 

```r
> mtcars |> tidytable::group_by(cyl) |> dplyr::mutate(vs = vs * n()) |> count(vs)
# A grouped tidytable: 2 × 2
     vs     n
  <dbl> <int>
1     0    18
2    32    14
> mtcars |> tidytable::group_by(cyl) |> tidytable::mutate(vs = vs * n()) |> count(vs)
# A grouped tidytable: 3 × 2
     vs     n
  <dbl> <int>
1     0    18
2     7     4
3    11    10
```

**Comment by moutikabdessabour** [comment]
the issue stems from the difference between the S3classes returned by each method. the solution could be as easy as adding `grouped_df` in the class of the returned `tidytable` (or maybe would require more work).

**Comment by statzhero** [comment]
Thanks! The development version of `dplyr` contains (so it says) a major speed improvement for the `dplyr::group_by()` function, so hopefully the gap will matter less. 

It would still be good to highlight this issue for novices; that is, one should not mix the two packages, especially now that they have the same function names throughout.

**Comment by markfairbanks** [comment]
@moutikabdessabour more or less covered the reasoning but I'll leave my answer as well.

`tidytable` and `dplyr` take a different approach to grouping. `tidytable` adds a simple character vector to show which columns are used in the grouping. These variables are then passed to the `by` arg of `data.table`. At its most basic a "tidytable" is a subclass of a "data.table" that leaves all heavy computational work to the `data.table` library. This includes group calculation.

``` r
library(tidytable, w = FALSE)

df <- tidytable(x = c("a", "a", "b"), y = c("a", "a", "b"), z = 1:3) %>%
  group_by(x, y)

class(df)
#> [1] "grouped_tt" "tidytable"  "data.table" "data.frame"

attr(df, "groups")
#> [1] "x" "y"
```

`dplyr` on the other hand is in charge of it's own grouping calculation. It's a subclass of a tibble, and attaches a data frame with grouping information to its own version of the "groups" attribute.

``` r
library(dplyr, w = FALSE)

df <- tibble(x = c("a", "a", "b"), y = c("a", "a", "b"), z = 1:3) %>%
  group_by(x, y)

class(df)
#> [1] "grouped_df" "tbl_df"     "tbl"        "data.frame"

attr(df, "groups")
#> # A tibble: 2 × 3
#>   x     y           .rows
#>   <chr> <chr> <list<int>>
#> 1 a     a             [2]
#> 2 b     b             [1]
```

`tidytable` doesn't generate this same data frame with grouping information because `data.table` doesn't.

@statzhero is there a reason you need to mix them?

**Comment by statzhero** [comment]
Thanks! Re your question: only legacy code. The problem is that eventually a `dplyr` function will always pop up, e.g. `dplyr::rows_patch()`, that is not supported (I think).

**Comment by markfairbanks** [comment]
Ah gotcha. You're right, the `rows_` functions aren't currently implemented in tidytable. I'll open an issue for those.

**Comment by markfairbanks** [comment]
In the future - when you do run into a function that isn't implemented can you open an issue to request them? It would help me to be sure I have everything implemented in `tidytable`.
