### ISSUE TITLE
calling str_replace_all inside mutate. throws 'argument "replacement" is missing' error in the latest build

### ISSUE THREAD

**Issue by mattsams89** [markfairbanks/tidytable#91]
This wasn't a problem until I pulled the latest version of tidytable (8837f2c8) from GitHub. My machine was running 0.5.1 before pulling the in-development 0.5.3. Further, reverting to 0.5.1 fixes the error while upgrading to 0.5.2 causes it to re-appear. Hopefully the following is enough of a reprex.

```
library(data.table)
library(tidytable)
library(stringr)

string_table <- 
tidytable(terms = c("Regular Video", "High Speed Video", 
                    "Rapsodo", "Pocket Radar", "Radar Gun", "None")) %>%
mutate.(terms = str_replace_all(terms, c("Regular Video" = "&#x1f4fc;")))
```

This also fails when attempting to run `str_replace_all` through `dt`, but works if run via data.table syntax. E.g. 
```
string_table[, terms := str_replace_all(terms, c("Regular Video" = "&#x1f4fc;"))]
``` 
or if I explicitly use `stringr::str_replace_all`.

I know it's coming from the utils-stringr internal version of `str_replace_all`, but I see those functions haven't been updated since February. I assume something is causing the internal version of the function to get called in place of stringr's version, although I haven't had the chance to comb through all the other changes between 0.5.1 -> now.

**Comment by markfairbanks** [comment]
Well this is a pretty interesting one.

**Short answer**
I need to rename internal functions to avoid naming conflicts. I know this sounds weird but this a problem that makes sense now that I see it, but I wouldn't have expected to occur.

**Long answer**
It's related to #63 which I was able to fix v0.5.0, but had to reopen due to performance issues. Essentially it boils down to this - quosures don't behave well with `data.table` (or base R). It's a limitation that Hadley & the tidyverse team knows about.

The way you get `data.table` code to work with `rlang` is you wrap the `data.table` expression like so:

```r
example_arrange <- function(.df, ...) {
  dots <- enexprs(...)
  
  eval_tidy(expr(
    .df[!!!dots]
  ))
}
```

This idea is how `tidytable` is built out.

That `eval_tidy(expr( ))` call allows you to use `rlang` `!!` or `!!!` with `data.table` or base R code. Now this implementation doesn't allow a user of the function to use the `{{ }}` shortcut (seen [here](https://github.com/markfairbanks/tidytable#rlang-compatibility)) to create custom functions. Well if we want the user to be able to do that we need quosures.

But as we talked about quosures don't work well with `data.table`. I had figured out a workaround in v0.5.0 to get them to work, but a side result was that it came with some huge performance losses that snuck past my normal speed tests. You can see some before/after speed tests in #82. As such I had to revert the changes in v0.5.2. However to allow the user to still use the `{{ }}` shortcut I used this workaround:

```r
example_arrange2 <- function(.df, ...) {
  dots <- enquos(...)
  
  eval_tidy(quo_squash(quo(
    .df[!!!dots]
  )))
}
```

That `quo_squash()` takes all quosures it finds inside and converts them to normal expressions. So the user can still use the `{{ }}` shortcut. This pattern is captured in an internal function called `eval_quo()` seen [here](https://github.com/markfairbanks/tidytable/blob/master/R/utils-general.R).

BUT - this no means we're no longer using quosures, which are much better than normal R expressions captured with `enexpr()`. 

So why does this matter?

Well as Hadley talks about, quosures also capture the environment an expression is defined in. In this case, the `str_replace_all()` in your `mutate.()` call was defined with `stringr`. But as I mentioned `tidytable` no longer uses quosures because of the huge performance issues it ended up causing.

So now the `mutate.()` call captures your expression and then just tries to evaluate it as is. And (somewhat oddly) uses the internal `str_replace_all()` as opposed to the `stringr` version that you're using in your R session. I will say it's rather unexpected behavior, but it's the reason it's occurring.

**Comment by mattsams89** [comment]
Gotcha. That also explains why I was having some issues with `!!` needing to be added in some places that were previously functional. `rlang` is black magic to me (read, I don't want to take the time to learn it) so I appreciate the deep dive of how you've managed to integrate with `data.table`! `tidytable` has definitely made it easier for me to communicate what I was previously doing with `data.table` syntax since my coworkers are exclusively Tidyverse users.

**Comment by markfairbanks** [comment]
All set:

``` r
library(tidytable, warn.conflicts = FALSE)
library(stringr)

string_table <-  tidytable(terms = c("Regular Video", "High Speed Video", 
                                     "Rapsodo", "Pocket Radar", "Radar Gun", "None"))

string_table %>%
  mutate.(terms = str_replace_all(terms, c("Regular Video" = "&#x1f4fc;")))
#>               terms
#> 1:        &#x1f4fc;
#> 2: High Speed Video
#> 3:          Rapsodo
#> 4:     Pocket Radar
#> 5:        Radar Gun
#> 6:             None
```
